-- Format for overwriting define values:
--
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0

NDefines.NEngine.MISSING_SCRIPTED_SUCCESSOR_ERROR_CUTOFF_YEAR = 583
NDefines.NEngine.MISSING_SCRIPTED_SUCCESSOR_ERROR_CUTOFF_MONTH = 1
NDefines.NEngine.MISSING_SCRIPTED_SUCCESSOR_ERROR_CUTOFF_DAY = 1

NDefines.NDiplomacy.LONG_REIGN_YEARS_START = 1000
NDefines.NDiplomacy.MAX_LONG_REIGN_BONUS = 0
NDefines.NDiplomacy.MAX_DIPLO_DISTANCE = 1300
NDefines.NDiplomacy.EVERY_DEFENSIVE_PACT_JOIN_THREAT = 1.01
NDefines.NDiplomacy.EVERY_DEFENSIVE_PACT_EXCEPT_HEADS_JOIN_THREAT = 0.9
NDefines.NDiplomacy.OTHER_DEFENSIVE_PACT_JOIN_THREAT = 0.8

NDefines.NCharacter.MAX_CHILD_BIRTH_AGE = 1000
NDefines.NCharacter.MALE_ATTRACTION_CUTOFF = 1000
NDefines.NCharacter.FEMALE_ATTRACTION_CUTOFF = 1000
NDefines.NCharacter.EARLY_PORTRAIT_AND_UNIT_BEFORE_YEAR = 500
NDefines.NCharacter.LATE_PORTRAIT_AND_UNIT_AFTER_YEAR = 600
NDefines.NCharacter.TREASURY_CHANCE_TO_DISAPPEAR_STANDARD = 0
NDefines.NCharacter.TREASURY_CHANCE_TO_DISAPPEAR_NO_HEIR = 0

NDefines.NEconomy.PATRICIAN_PRESTIGE_RESPECT_FACTOR = 5
NDefines.NEconomy.PATRICIAN_AGE_RESPECT_FACTOR = 0.01

NDefines.NMilitary.NUM_DAYS_BETWEEN_SIEGE_MORALE_LOSS = 6
NDefines.NMilitary.BASE_SETTLEMENT_WARSCORE = 0.25
NDefines.NMilitary.ARMY_MOVEMENT_SPEED = 3
NDefines.NMilitary.NAVY_MOVEMENT_SPEED = 30

NDefines.NTechnology.DONT_EXECUTE_TECH_BEFORE = 150
NDefines.NTechnology.IDEAL_YEAR_LEVEL_0 = 150
NDefines.NTechnology.IDEAL_YEAR_LEVEL_8 = 950

NDefines.NEndGame.DYN1_ID = 0
NDefines.NEndGame.DYN2_SCORE = 100000
NDefines.NEndGame.DYN2_ID = 0
NDefines.NEndGame.DYN3_SCORE = 99000
NDefines.NEndGame.DYN3_ID = 0
NDefines.NEndGame.DYN4_SCORE = 98000
NDefines.NEndGame.DYN4_ID = 0
NDefines.NEndGame.DYN5_SCORE = 97000
NDefines.NEndGame.DYN5_ID = 0
NDefines.NEndGame.DYN6_SCORE = 96000
NDefines.NEndGame.DYN6_ID = 0
NDefines.NEndGame.DYN7_SCORE = 95000
NDefines.NEndGame.DYN7_ID = 0
NDefines.NEndGame.DYN8_SCORE = 94000
NDefines.NEndGame.DYN8_ID = 0
NDefines.NEndGame.DYN9_SCORE = 92000
NDefines.NEndGame.DYN9_ID = 0
NDefines.NEndGame.DYN10_SCORE = 91000
NDefines.NEndGame.DYN10_ID = 0
NDefines.NEndGame.DYN11_SCORE = 90000
NDefines.NEndGame.DYN11_ID = 0
NDefines.NEndGame.DYN12_SCORE = 89000
NDefines.NEndGame.DYN12_ID = 0
NDefines.NEndGame.DYN13_SCORE = 88000
NDefines.NEndGame.DYN13_ID = 0
NDefines.NEndGame.DYN14_SCORE = 87000
NDefines.NEndGame.DYN14_ID = 0
NDefines.NEndGame.DYN15_SCORE = 86000
NDefines.NEndGame.DYN15_ID = 0

NDefines.NRulerDesigner.MAX_AGE = 30

NDefines.NAI.AI_EMPEROR_CREATES_KINGDOMS = 1
NDefines.NAI.MAX_KING_TITLES_TO_CREATE = 3